# Generated by Django 5.2.4 on 2025-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaleoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessionnumber',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
