# Generated by Django 5.2.4 on 2025-07-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaleoApp', '0003_conflictlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='end_range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='start_range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
